### ISSUE TITLE
Mod Incompatibility Stuff the Spire

### ISSUE THREAD

**Issue by lobbienjonsji** [EatYourBeetS/STS-AnimatorMod#3]
When the animator is installed, the Paper Kängäröö crashes when it procs, even if the player is not playing as the animator. The code for the Kängäröö: https://github.com/lobbienjonsji/StuffTheSpire/blob/master/src/main/java/StuffTheSpire/relics/PaperKangaroo.java

**Comment by EatYourBeetS** [comment]
with `!(p instanceof InvisiblePower)` this should be solved
